name: Compile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      - name: Build
        run: npm run build

      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'css/*'
          message: 'Add built artefacts'
