name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    concurrency: la-web-components
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        with:
          # use a token that has admin perms to bypass direct commits to master
          token: ${{ secrets.LA_ACTIONS_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install all dependencies
        run: | # Install and link dependencies
          npm ci
          npx lerna bootstrap

      - name: Build
        run: |
          npx lerna run build

      - name: Push build artefacts
        uses: EndBug/add-and-commit@v9
        with:
          add: 'core/dist/ law-widget-styles/css/law-widget-styles.* --force'
          message: 'Built artefacts'

      - name: Build storybook
        run: | # Build storybook
          cd ./core
          npm run build-storybook

      - name: Publish Storybook
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: core/storybook-static
