name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    concurrency: la-web-components
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          # use a token that has admin perms to bypass direct commits to main
          token: ${{ secrets.LA_ACTIONS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm ci
      - run: npx lerna bootstrap
      - run: npx lerna run build

      - name: Push build artefacts
        uses: EndBug/add-and-commit@v9
        with:
          add: 'law-widget-styles/css/law-widget-styles.* --force'
          message: 'Built artefacts'
