name: Compile and commit to dist

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    concurrency: la-web-components
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          # use a token that has admin perms to bypass direct commits to master
          token: ${{ secrets.LA_ACTIONS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install all dependencies
        run: | # Install and link dependencies
          npm ci
          npx lerna bootstrap

      - name: Build Law Widget Styles
        run: cd ./law-widget-styles && npm run build

      - name: Build storybook
        run: cd ./core && npm run build && npm run build-storybook

      - name: Publish Storybook
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static/
          SINGLE_COMMIT: true
