name: Unit Tests

on:
  push:
    branches:
      - "*"

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npx lerna run test
